version: '3.1'

services:
    db:
        image: postgis/postgis:15-3.3
        restart: "no"
        environment:
            POSTGRES_DB: wish
            POSTGRES_USER: test
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - ./data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        restart: "no"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: password
            PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'True'
        ports:
            - "5050:80"

    geoserver:
        image: kartoza/geoserver:latest
        environment:
            GEOSERVER_DATA_DIR: /opt/geoserver/data_dir
            GEOSERVER_ADMIN_USER: admin
            GEOSERVER_ADMIN_PASSWORD: geoserver
            POSTGRES_DB: wish
            POSTGRES_USER: test
            POSTGRES_PASSWORD: password
            POSTGRES_HOST: db
            POSTGRES_PORT: 5432
        ports:
            - "8081:8080"
        volumes:
            - ./geoserver_data:/opt/geoserver/data_dir

volumes:
  data:
    name: wish_data
